meta:
  version: 2
  width: 120
  height: 22
  timestamp: 1707604909
  env:
    SHELL: "/bin/bash"
    TERM: "xterm-256color"

prompt:
  wait:
    before: 0
    after: 0.75

group:
  wait:
    before: 0
    after: 0

item:
  wait:
    before: 0
    after: 0.1

char:
  wait:
    before: 0
    after: 0.05
